### PR TITLE
fixed spelling and grammar issues

### PR DESCRIPTION
**Pull request by zackarhino**
I fixed a few typos on the website and clarified sentences that were unclear.

### CODE REVIEW

**Comment by pedronauck** [comment]
thanks your pr @zackarhino 🙏 but please, set your register to be npm instead of yarnpkg, because your pr overwrites somelines of `yarn.lock`

**Comment by zackarhino** [comment]
I'm not exactly sure how to do that. I'm new to contributing to open source.

**Comment by pedronauck** [comment]
for sure @zackarhino, now you need to run `yarn install` again, then commit and push on your repo again ✌️

**Comment by zackarhino** [comment]
Is it possible to just copy the yarn.lock file from this repo to my fork to remove the conflict? I've never worked with yarn before so I'm not too sure how it works.

**Pull request merged**
